/*
 * File: app/store/OptionsStore.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HUDTenant.store.OptionsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'HUDTenant.model.Option',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Array'
    ],

    config: {
        autoLoad: true,
        data: [
            [
                1,
                'Fair Market Rent'
            ],
            [
                2,
                'Contact Us'
            ],
            [
                3,
                'Tell a Fried'
            ]
        ],
        model: 'HUDTenant.model.Option',
        storeId: 'OptionsStore',
        proxy: {
            type: 'memory',
            reader: {
                type: 'array'
            }
        }
    }
});