/*
 * File: app/view/FMRForm.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HUDTenant.view.FMRForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Number'
    ],

    config: {
        id: 'fmr-form',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Fair Market Rent',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            var main = Ext.getCmp('main');

                            if (main === undefined){
                                main = Ext.getCmp('fmrs');
                            }
                            Ext.Viewport.setActiveItem(main);
                        },
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Locality',
                        name: 'LocalityName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'MSA',
                        name: 'MetropolitanAreaName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Efficiency',
                        labelWidth: '50%',
                        name: 'Efficiency',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'One Bedroom',
                        labelWidth: '50%',
                        name: 'OneBedroom',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Two Bedroom',
                        labelWidth: '50%',
                        name: 'TwoBedroom',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Three Bedroom',
                        labelWidth: '50%',
                        name: 'ThreeBedroom',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Four Bedroom',
                        labelWidth: '50%',
                        name: 'FourBedroom',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'FMR Percentile',
                        labelWidth: '50%',
                        name: 'FMRPercentile',
                        readOnly: true
                    }
                ]
            }
        ]
    }

});