/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HUDTenant.view.MainView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainview',

    requires: [
        'HUDTenant.view.PhasView',
        'HUDTenant.view.Options',
        'Ext.Panel',
        'Ext.tab.Bar'
    ],

    config: {
        id:'main-view',
        items: [
            {
                title: 'Welcome',
                iconCls: 'home',
                cls: 'home',

                styleHtmlContent: true,
                scrollable: true,

                items: {
                    docked: 'top',
                    xtype: 'titlebar',
                    title: 'Welcome to HUD Tenant'
                },

                html: [
                    '<h1>Welcome to HUD Tenant</h1>',
                    '<p>We have created an app so you can calculate your Tenant Rent for public housing or Section 8 Hud Programs based on simple questions.</p>',
                    '<p>In order to be more accurate you should follow the instructions in "Instructions tab" carefully.</p>',
                    '<p>We also will have a pro version where you can put more detailed',
                    ' information so the calculations will be more accurate.</p>',
                    '</div>'
                ].join("")
            },
            {
                xtype:'tenantview'
            },
            {
                xtype: 'container',
                title: 'Phas',
                iconCls: 'info',
                layout: 'fit',
                items: [
                    {
                        xtype: 'phasview'
                    }
                ]
            },
            {
                xtype:'instructions'
            },
            {
                xtype: 'container',
                title: 'More Options',
                iconCls: 'more',
                layout: 'fit',
                items: [
                    {
                        xtype: 'options'
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});